/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:c4ad3f5c-2dff-4e41-baa4-a86aacd63cba",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_sKvFAlZ2U",
    "aws_user_pools_web_client_id": "50ep3jhi2t05c7stc5s2c03snc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://g52dkzwnhbgzro7mvqrloftkg4.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "photoalbums6d00c30c0dd34f9e939bfee1b45ae1d495624-master",
    "aws_user_files_s3_bucket_region": "ap-northeast-2"
};


export default awsmobile;
